name: virtual_event_app
description: "A virtual event platform built with Flutter."
# Prevent accidental publishing to pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# ------------------- DEPENDENCIES ------------------- #
dependencies:
  flutter:
    sdk: flutter

  # --- Firebase & Google Sign-In ---
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.5

  # --- State Management & Navigation ---
  provider: ^6.1.2
  go_router: ^14.1.2

  # --- Security & Two-Factor Authentication (2FA) ---
  otp: ^3.1.4
  qr_flutter: ^4.1.0

  # --- UI & Components ---
  table_calendar: ^3.1.2
  intl: ^0.19.0 # For date/time formatting
  flutter_spinkit: ^5.2.1 # For loading indicators
  
  # --- Utilities & Helpers ---
  equatable: ^2.0.5 # For value equality in models without boilerplate
  url_launcher: ^6.2.6 # NEEDED to launch the authenticator app

# ---------------- DEV DEPENDENCIES ---------------- #
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints
  # to encourage good coding practices.
  flutter_lints: ^3.0.0

# ----------------- FLUTTER CONFIG ----------------- #
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/google_logo.png