// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Q0zf6e2tZWvYXHfqgN5n2qi0rwH-2CQ',
    appId: '1:740893431159:web:3924a31da6e88eb607bd72',
    messagingSenderId: '740893431159',
    projectId: 'virtual-event-app-cfbdd',
    authDomain: 'virtual-event-app-cfbdd.firebaseapp.com',
    storageBucket: 'virtual-event-app-cfbdd.firebasestorage.app',
    measurementId: 'G-6B6JLSR1MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmgARMwjNdwuBMv3zjQ3MQUtfHQxq5GEM',
    appId: '1:740893431159:android:3c3791d1783d4bf207bd72',
    messagingSenderId: '740893431159',
    projectId: 'virtual-event-app-cfbdd',
    storageBucket: 'virtual-event-app-cfbdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNCwpKhV04J3F8SxugV-PTgXOSp8MoZNE',
    appId: '1:740893431159:ios:0eaa65f4d525891d07bd72',
    messagingSenderId: '740893431159',
    projectId: 'virtual-event-app-cfbdd',
    storageBucket: 'virtual-event-app-cfbdd.firebasestorage.app',
    iosBundleId: 'com.example.virtualEventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNCwpKhV04J3F8SxugV-PTgXOSp8MoZNE',
    appId: '1:740893431159:ios:0eaa65f4d525891d07bd72',
    messagingSenderId: '740893431159',
    projectId: 'virtual-event-app-cfbdd',
    storageBucket: 'virtual-event-app-cfbdd.firebasestorage.app',
    iosBundleId: 'com.example.virtualEventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Q0zf6e2tZWvYXHfqgN5n2qi0rwH-2CQ',
    appId: '1:740893431159:web:803a1811c17c8c8d07bd72',
    messagingSenderId: '740893431159',
    projectId: 'virtual-event-app-cfbdd',
    authDomain: 'virtual-event-app-cfbdd.firebaseapp.com',
    storageBucket: 'virtual-event-app-cfbdd.firebasestorage.app',
    measurementId: 'G-MZX1WPQ660',
  );
}
